services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=first-move
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
        ports:
            - 5332:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        ports:
            - 16543:80
        volumes:
            - ./postgres-servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network

networks:
    postgres-db-network:
        driver: bridge
